name: Deploy Static Website

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  deploy:
    name: Deploy to Shared Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.FTP_SERVER }}   # Your hosting FTP server (e.g., ftp.example.com)
          username: ${{ secrets.FTP_USERNAME }}  # Your FTP username
          password: ${{ secrets.FTP_PASSWORD }}  # Your FTP password
          local-dir: ./  # Folder containing static site files (default repo root)
          server-dir: /public_html/  # Path on the server where files should be uploaded
          exclude: |
            **/.git*
            **/.github*
            **/README.md
            **/node_modules

